### PR TITLE
Update dependencies & setup dependabot to monitor outdated

### PR DESCRIPTION
**Pull request by slonopotamus**
1. This PR depends on #178
2. I didn't update `clap` because that involves massive code changes and better be done separately

### CODE REVIEW

**Comment by volks73** [comment]
@slonopotamus PR #178 has been merged. Can you update this PR to have the tests and clippy pass?

**Comment by volks73** [comment]
The failing tests are from #146. If the minimum Rust version is going to be bumped, this issue needs to be addressed.

**Comment by slonopotamus** [comment]
I'm not sure failures are related to #146. Need to investigate this a bit more.

**Comment by slonopotamus** [comment]
The issue was that semantics of `toml::from_str` have changed and now the proper way to deserialize TOML is `"...".parse::<Table>()`. Now tests fully pass.

**Review by volks73 — APPROVED** [review]
Looks good.

**Pull request merged**
