### PR TITLE
Add a --profile flag to be more general than --debug-build

### PR DESCRIPTION
**Pull request by Gankra**
This also does some driveby fixes to add `.action(ArgAction::SetTrue))` to a bunch of --flags because a breaking change was made to clap:

https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating

-----

I'm experimenting with adding support for cargo-wix, but to avoid duplicate builds I want to use --no-build (and as far as I can tell cargo-wix doesn't set any particularly special cargo/rust build flags, so we aren't messing up something important by doing that).

However cargo-dist sets --profile=dist which changes the directory the binaries end up in, so I need cargo-wix to be able to take an arbitrary `--profile`. Thankfully this is very easy to do, as you already made all your logic work with an abitrary profile string.

For the record the specific invocation I would use would look like:

```
cargo wix --no-build --profile=dist --target=x86_64-pc-windows-msvc -o target/distrib/cargodisttest.msi
```

### CODE REVIEW

**Review by volks73 — APPROVED** [review]
Thank you for the PR.

I understand the need and I like the flexibility with defining other profiles.

I am not sure what is going on with the tests and CI. Would you be able to take a look and possibly add a test that uses the new `--profile` argument?

**Comment by Gankra** [comment]
pushed a potential fix (only the dependency change really matters, but figured I'd toss in the rest)

**Comment by Gankra** [comment]
Oh right, tests, will do.

**Comment by Gankra** [comment]
Great call on the tests -- I had tested things pretty thoroughly for my exact usecase but completely blanked on testing (and apparently implementing!) actual builds. Some extra logic was required to deal with the mismatch between builtin profile names and the output dirs they go to.

I also fixed some broken doctests, because your CI wasn't testing docs (unfortunately [according to cargo test's docs](https://doc.rust-lang.org/cargo/commands/cargo-test.html), `--all-targets` is a trick:

```
--all-targets
    Test all targets. This is equivalent to specifying --lib --bins --tests --benches --examples.

--doc
    Test only the library’s documentation. This cannot be mixed with other target options. 
```

Running rustdoc with -Dwarnings gets the desired functionality, so I added that to your CI.

**Comment by volks73** [comment]
Thank you for tests. They are really appreciated and look great.

I missed the doc builds for the CI. Nice catch. This is ready merge. Thank you.

**Comment by KGrewal1** [comment]
Hi - was looking for this setting and found this PR - is this documented anywhere, the docs don't appear to have this!

**Comment by volks73** [comment]
@KGrewal1 The online documentation might be out-of-sync. The `--help` documentation is the "source of truth" for supported functionality and flags. It does appear the online documentation is missing any mention of this feature.

**Pull request merged**
