### PR TITLE
Add support for --output <directory>

### LINKED ISSUE #79: Add support for --output <directory>
[cargo-deb](https://github.com/mmstick/cargo-deb) has a nice feature: when you run `cargo deb --output target/dir/` with last component either ending with slash or pointing to existing directory, `cargo-deb` uses that dir instead of default but still does its own magic of generating file name based on crate name/version/architecture.

Here's the code that they use: https://github.com/mmstick/cargo-deb/blob/75a27c257dc78c5f87be708be929e4e83b44066c/src/manifest.rs#L475

Currently:

1. If you run `cargo-wix --output <existing directory>`, light.exe exists with error:
```light.exe : error LGHT0281 : The -out option requires a file```
2. If you run `cargo-wix --output <nonexistent directory>/`, cargo-wix completes successfully, directory is created, but msi is named just `.msi`, without crate name/version/architecture.

### PR DESCRIPTION
**Pull request by slonopotamus**
Fixes #79

### CODE REVIEW

**Comment by volks73** [comment]
Thanks for the PR and including a test case! I am going to merge this PR as is, but the following things need to be addressed.

The `-o,--output` short and long help for the CLI should be updated for the create (default) command to reflect the new behavior, along with the doc comments.

I would also like to change the test case and expand the number of tests to account for the variety of values that are possible for the `-o,--output <output>` option:

```rust
#[test]
fn output_trailing_forwardslash_works() {
    let output_dir = PathBuf::from(TARGET_NAME).join("output_dir");
    let output_dir_str = format!("{}/", output_dir.to_str().unwrap());
    let original_working_directory = env::current_dir().unwrap();
    let package = common::create_test_package();
    let expected_msi_file = output_dir.join(format!("{}-0.1.0-x86_64.msi", PACKAGE_NAME));
    env::set_current_dir(package.path()).unwrap();
    initialize::Execution::default().run().unwrap();
    let result = Builder::new()
        .output(Some(output_dir_str.as_str()))
        .build()
        .run();
    env::set_current_dir(original_working_directory).unwrap();
    result.expect("OK result");
    package
        .child(TARGET_WIX_DIR.as_path())
        .assert(predicate::path::exists());
    package
        .child(expected_msi_file)
        .assert(predicate::path::exists());
}

#[test]
fn output_trailing_backslash_works() {
    let output_dir = PathBuf::from(TARGET_NAME).join("output_dir");
    let output_dir_str = format!("{}\\", output_dir.to_str().unwrap());
    let original_working_directory = env::current_dir().unwrap();
    let package = common::create_test_package();
    let expected_msi_file = output_dir.join(format!("{}-0.1.0-x86_64.msi", PACKAGE_NAME));
    env::set_current_dir(package.path()).unwrap();
    initialize::Execution::default().run().unwrap();
    let result = Builder::new()
        .output(Some(output_dir_str.as_str()))
        .build()
        .run();
    env::set_current_dir(original_working_directory).unwrap();
    result.expect("OK result");
    package
        .child(TARGET_WIX_DIR.as_path())
        .assert(predicate::path::exists());
    package
        .child(expected_msi_file)
        .assert(predicate::path::exists());
}

#[test]
fn output_existing_dir_works() {
    let output_dir = PathBuf::from("output_dir");
    let original_working_directory = env::current_dir().unwrap();
    let package = common::create_test_package();
    let expected_msi_file = output_dir.join(format!("{}-0.1.0-x86_64.msi", PACKAGE_NAME));
    env::set_current_dir(package.path()).unwrap();
    fs::create_dir(&output_dir).unwrap();
    initialize::Execution::default().run().unwrap();
    let result = Builder::new()
        .output(output_dir.to_str())
        .build()
        .run();
    env::set_current_dir(original_working_directory).unwrap();
    result.expect("OK result");
    package
        .child(TARGET_WIX_DIR.as_path())
        .assert(predicate::path::exists());
    package
        .child(expected_msi_file)
        .assert(predicate::path::exists());
}

#[test]
fn output_file_without_extension_works() {
    let output_dir = PathBuf::from(TARGET_NAME).join("output_dir");
    let original_working_directory = env::current_dir().unwrap();
    let package = common::create_test_package();
    let output_file = output_dir.join(PACKAGE_NAME);
    let expected_msi_file = output_dir.join(format!("{}.msi", PACKAGE_NAME));
    env::set_current_dir(package.path()).unwrap();
    initialize::Execution::default().run().unwrap();
    let result = Builder::new()
        .output(output_file.to_str())
        .build()
        .run();
    env::set_current_dir(original_working_directory).unwrap();
    result.expect("OK result");
    package
        .child(TARGET_WIX_DIR.as_path())
        .assert(predicate::path::exists());
    package
        .child(expected_msi_file)
        .assert(predicate::path::exists());
}

#[test]
fn output_file_with_extension_works() {
    let output_dir = PathBuf::from(TARGET_NAME).join("output_dir");
    let original_working_directory = env::current_dir().unwrap();
    let package = common::create_test_package();
    let expected_msi_file = output_dir.join(format!("{}.msi", PACKAGE_NAME));
    env::set_current_dir(package.path()).unwrap();
    initialize::Execution::default().run().unwrap();
    let result = Builder::new()
        .output(expected_msi_file.to_str())
        .build()
        .run();
    env::set_current_dir(original_working_directory).unwrap();
    result.expect("OK result");
    package
        .child(TARGET_WIX_DIR.as_path())
        .assert(predicate::path::exists());
    package
        .child(expected_msi_file)
        .assert(predicate::path::exists());
}
```

These might be better served as unit tests for the `destination_msi` method, but more integration tests should not hurt.

**Comment by slonopotamus** [comment]
Do you want me to make these changes and send another PR or you'll do them?

It actually would be ok if you did NOT merge until I made required changes :)

**Comment by volks73** [comment]
Sorry, I am already in the process and completed most of the changes. I will be pushing the updates momentarily.

**Comment by slonopotamus** [comment]
No problem!

**Pull request merged**
